server:
  port: 10088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data?serverTimezone=Asia/Shanghai&allowMultiQueries=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/insurance
